platform :ios, '9.0'

use_frameworks!
inhibit_all_warnings!

target 'CHLMVP_Example' do
  pod 'CHLMVP', :path => '../'
  pod 'Alamofire', '4.7.3'

  target 'CHLMVP_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
